# Python index start from 0 and MATLAB index start from 1. So, we need to subtract 1 from the MATLAB index to get the Python index.
# Following are the parameters for the model.
params_avg: # Parameters for the average data set from 53 patients.
  p_c: [0.027, 0.035, 0.808, 1.52, 0.16, 0.16] # p_c[0:4] are the proliferation rate of HSC, MPP, CMP, and MEP. p_c[4:6] are the endomitosis duration for megakaryoblast and megakaryocayte.
  a_c: [0.877, 0.854, 0.853, 0.688] # self-renewal probability of HSC, MPP, CMP, and MEP.
  k_p: 1.4e-9 # Postive constant factor of the feedback signal that affect proliferation rate.
  k_a: 5.4e-11 # Positive constant factor of the feedback signal that affect self-renewal probability.
  d_plt: 0.19 # Platelets clearance rate.
  k_decline: 0.345 # Residual platelets clearance rate.
  k_shed: 1037 # Shedding factor of megakaryocytes.

# Later parameters are for individual patients. They follow the same format as we use for the average data set.
# Some patients are lack of the platelets data at day 0, so we use the curve fitting(f=ae^(-bx))result 'a' from MATLAB as the initial value for c[7], residual platelets and b is the value for k_decline.
# Based on identifiability analysis, these parameters value are fixed during optimization:
# p_c[0]=0.027, p_c[1]=0.035, p_c[3]=1.52, a_c[0]=0.877, k_p=1.4e-9, d_plt=0.19, k_shed=1037

# Slow group:
params_pat1:
    p_c: [0.027, 0.035, 0.407, 1.52, 0.160, 0.160]
    a_c: [0.877, 0.853, 0.861, 0.659]
    k_p: 1.4e-9
    k_a: 7.28e-11
    d_plt: 0.19
    k_decline: 0.497
    k_shed: 1037

params_pat7:
    p_c: [0.027, 0.035, 0.252, 1.52, 0.16, 0.16]
    a_c: [0.877, 0.853, 0.859, 0.512]
    k_p: 1.4e-9
    k_a: 1.21e-10
    d_plt: 0.19
    k_decline: 0.289
    k_shed: 1037
    plt_start: 91

params_pat13:
    p_c: [0.027, 0.035, 0.529, 1.52, 0.160, 0.160]
    a_c: [0.877, 0.853, 0.866, 0.482]
    k_p: 1.4e-9
    k_a: 7.50e-11
    d_plt: 0.19
    k_decline: 0.357
    k_shed: 1037

params_pat17:
    p_c: [0.027, 0.035, 0.223, 1.52, 0.160, 0.160]
    a_c: [0.877, 0.853, 0.857, 0.532]
    k_p: 1.4e-9
    k_a: 1.30e-10
    d_plt: 0.19
    k_decline: 1.044
    k_shed: 1037

# Fast group:
params_pat15:
    p_c: [0.027, 0.035, 0.890, 1.52, 0.163, 0.164]
    a_c: [0.877, 0.853, 0.525, 0.870]
    k_p: 1.4e-9
    k_a: 4.21e-11
    d_plt: 0.19
    k_decline: 0.235
    k_shed: 1037

params_pat36:
    p_c: [0.027, 0.035, 1.105, 1.52, 0.165, 0.165]
    a_c: [0.877, 0.853, 0.862, 0.747]
    k_p: 1.4e-9
    k_a: 4.19e-11
    d_plt: 0.19
    k_decline: 0.418
    k_shed: 1037
    plt_start: 37

params_pat37:
    p_c: [0.027, 0.035, 1.516, 1.52, 1.083, 0.144]
    a_c: [0.877, 0.853, 0.873, 0.306]
    k_p: 1.4e-9
    k_a: 3.16e-11
    d_plt: 0.19
    k_decline: 0.546
    k_shed: 1037
    plt_start: 331

params_pat49:
    p_c: [0.027, 0.035, 1.513, 1.52, 0.232, 0.237]
    a_c: [0.877, 0.853, 0.031, 0.874]
    k_p: 1.4e-9
    k_a: 2.85e-11
    d_plt: 0.19
    k_decline: 0.465
    k_shed: 1037

# Other patients:
